import type { HouseDetail } from "../model/HouseDetail.ts";
import { ApartmentStatus } from "../model/ApartmentStatus.ts";
import { HouseType } from "./HouseTypes.ts";

export const data: HouseDetail[] = [
  {
    id: "alzbeta",
    name: "Dům Alžběta",
    position: { x: 12, y: 3 },
    type: HouseType.A,
    apartments: [
      {
        id: "RD1B1",
        number: "RD1B1",
        layout: "3+kk",
        usable_area: 97.74,
        totalArea: 103.67,
        balcony: 9,
        garden: 171.33,
        storage: 9.35,
        garage: 1,
        price: 16073870,
        status: ApartmentStatus.Sold,
      },
      {
        id: "RD1B2",
        number: "RD1B2",
        layout: "3+kk",
        usable_area: 68.45,
        totalArea: 72.82,
        balcony: 0,
        garden: 171.33,
        storage: 8.7,
        garage: 1,
        price: 11828209,
        status: ApartmentStatus.Sold,
      },
      {
        id: "RD1B3",
        number: "RD1B3",
        layout: "2+1",
        usable_area: 63.07,
        totalArea: 67.15,
        balcony: 0,
        garden: 171.33,
        storage: 8.7,
        garage: 1,
        price: 11445521,
        status: ApartmentStatus.Sold,
      },
    ],
  },
  {
    id: "barbora",
    name: "Dům Barbora",
    position: { x: 3.5, y: 8 },
    type: HouseType.B,
    apartments: [
      {
        id: "RD2B1",
        number: "RD2B1",
        layout: "3+kk",
        usable_area: 97.74,
        totalArea: 103.67,
        balcony: 9,
        garden: 170.33,
        storage: 9.35,
        garage: 1,
        price: 16370494,
        status: ApartmentStatus.Sold,
      },
      {
        id: "RD2B2",
        number: "RD2B2",
        layout: "3+kk",
        usable_area: 68.45,
        totalArea: 72.82,
        balcony: 0,
        garden: 170.33,
        storage: 8.7,
        garage: 1,
        price: 11826739,
        status: ApartmentStatus.Free,
      },
      {
        id: "RD2B3",
        number: "RD2B3",
        layout: "2+1",
        usable_area: 63.07,
        totalArea: 67.15,
        balcony: 0,
        garden: 170.33,
        storage: 8.7,
        garage: 1,
        price: 11239361,
        status: ApartmentStatus.InReservation,
      },
    ],
  },
  {
    id: "cecilie",
    name: "Dům Cecílie",
    position: { x: 1.9, y: 6 },
    type: HouseType.A,
    apartments: [
      {
        id: "RD3B1",
        number: "RD3B1",
        layout: "3+kk",
        usable_area: 97.74,
        totalArea: 103.67,
        balcony: 9,
        garden: 180.0,
        storage: 9.35,
        garage: 1,
        price: 16085958,
        status: ApartmentStatus.Free,
      },
      {
        id: "RD3B2",
        number: "RD3B2",
        layout: "3+kk",
        usable_area: 68.45,
        totalArea: 72.82,
        balcony: 0,
        garden: 180.0,
        storage: 8.7,
        garage: 1,
        price: 11840952,
        status: ApartmentStatus.Free,
      },
      {
        id: "RD3B3",
        number: "RD3B3",
        layout: "2+1",
        usable_area: 63.07,
        totalArea: 67.15,
        balcony: 0,
        garden: 180.0,
        storage: 8.7,
        garage: 1,
        price: 11253911,
        status: ApartmentStatus.Sold,
      },
    ],
  },
  {
    id: "dana",
    name: "Dům Dana",
    type: HouseType.B,
    position: { x: 1.3, y: 6 },
    apartments: [
      {
        id: "RD4B1",
        number: "RD4B1",
        layout: "3+kk",
        usable_area: 97.74,
        totalArea: 103.67,
        balcony: 9,
        garden: 174.8,
        storage: 9.35,
        garage: 1,
        price: 16376845,
        status: ApartmentStatus.Free,
      },
      {
        id: "RD4B2",
        number: "RD4B2",
        layout: "3+kk",
        usable_area: 68.45,
        totalArea: 72.82,
        balcony: 0,
        garden: 174.8,
        storage: 8.7,
        garage: 1,
        price: 11615095,
        status: ApartmentStatus.InReservation,
      },
      {
        id: "RD4B3",
        number: "RD4B3",
        layout: "2+1",
        usable_area: 63.07,
        totalArea: 67.15,
        balcony: 0,
        garden: 174.8,
        storage: 8.7,
        garage: 1,
        price: 11041329,
        status: ApartmentStatus.Free,
      },
    ],
  },
  {
    id: "eliska",
    name: "Dům Eliška",
    position: { x: 1.3, y: 1.7 },
    type: HouseType.A,
    apartments: [
      {
        id: "RD5B1",
        number: "RD5B1",
        layout: "3+kk",
        usable_area: 97.74,
        totalArea: 103.67,
        balcony: 9,
        garden: 186.0,
        storage: 9.35,
        garage: 1,
        price: 16094327,
        status: ApartmentStatus.Free,
      },
      {
        id: "RD5B2",
        number: "RD5B2",
        layout: "3+kk",
        usable_area: 68.45,
        totalArea: 72.82,
        balcony: 0,
        garden: 186.0,
        storage: 8.7,
        garage: 1,
        price: 11631241,
        status: ApartmentStatus.InReservation,
      },
      {
        id: "RD5B3",
        number: "RD5B3",
        layout: "2+1",
        usable_area: 63.07,
        totalArea: 67.15,
        balcony: 0,
        garden: 186.0,
        storage: 8.7,
        garage: 1,
        price: 11057861,
        status: ApartmentStatus.Free,
      },
    ],
  },
];
